### ISSUE TITLE
Enable pipeline triggering and execution status tracking

### ISSUE THREAD

**Issue by boscard** [codilime/floodgate#106]
It would be nice to have an option to trigger pipeline for example using webhook and be able to track status execution using Floodgate.

Currently I need to use curl to trigger webhook, and then with combination of spin and curl command I'm able to track execution status.
I believe that Floodgate could do this on its own.

It could look like this:
```
$ floodgate execute deploy-nging-webhook -p parameters.json
triggering 'deploy-nging-webhook'
waiting for execution id................
execution id is 12345463DCAF
execution status: RUNNING.....................
pipeline finished with status: FAILED
$ echo $?
1
```

**Comment by wurbanski** [comment]
Maybe make sure that we can either wait for the execution to finish or not?
