### ISSUE TITLE
Build Floodgate with different Spinnaker versions

### ISSUE THREAD

**Issue by boscard** [codilime/floodgate#17]
We should be able to build Floodgate with all supported Spinnaker gateapi versions. Usually it is current version and two previous versions.

**Comment by boscard** [comment]
@wurbanski I think, that this was resolved by #21 . We are building Floodgate one a day with Gate API for Spinnaker v1.19, v1.18 and v.1.17.

**Comment by wurbanski** [comment]
I think you're right, let's just see it work at least once to be sure :)
